# conda env create --file environment.yml

name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  {% if cookiecutter.project_packages == "All" -%}
  - fs
  {% endif -%}
  - invoke
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  {% if cookiecutter.project_packages == "All" -%}
  - pathlib
  {% endif -%}
  - pip
  - plotly
  {% if cookiecutter.project_packages == "All" -%}
  - pyhere
  - pyprojroot
  {% endif -%}
  - python={{ cookiecutter.python_version }}
  - scipy
  - seaborn
  - sklearn 